//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadlyDatabaseToJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment_data
    {
        public int appointment_id { get; set; }
        public int patient_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> scheduled { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    
        public virtual patient_data patient_data { get; set; }
    }
}
